require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'config/boot.rb'
    - 'config/puma.rb'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'

Layout/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false

Style/RedundantConstantBase:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either
