name: Styles check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@4d060a10e6d98429c69057f0aafbc65fb982bae8
        with:
          bundler-cache: true
      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7

      - name: Run ESLint
        run: yarn eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
